# Generated by Django 4.0.3 on 2022-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_category_ico_category_categoryico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryico',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
